config/routes.rb
Rails.application.routes.draw do
  root to: "categories#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  resources :categories, only: %i[index show new create] do
    resources :bookmarks, only: %i[new create]
  end
  resources :bookmarks, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :recipe
  belongs_to :category
  # A bookmark must be linked to a recipe and a category, and the [recipe, category] pairings should be unique.
  validates :recipe_id, uniqueness: { scope: :category_id }
  # The comment of a bookmark cannot be shorter than 6 characters.
  validates :comment, length: { minimum: 6 }
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :recipes, through: :bookmarks
  has_one_attached :photo
  # A category must have a unique name.
  validates :name, uniqueness: true
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  has_many :bookmarks
  # A recipe must have a description and a unique name.
  validates :description, presence: true
  validates :name, presence: true, uniqueness: true
  # The rating of a recipe must be a value between 0 and 5.
  validates :rating, numericality: { in: 0..5 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def new
    @category = Category.find(params[:category_id])
    @bookmark = Bookmark.new
  end

  def create
    category_id = params[:category_id]
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.category_id = category_id
    if @bookmark.save
      redirect_to category_path(category_id)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
    redirect_to category_path(@bookmark.category)
  end


  private

  def bookmark_params
    params.require(:bookmark).permit(:comment, :recipe_id)
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.all
  end

  def show
    @category = Category.find(params[:id])
    @bookmarks = @category.bookmarks
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      redirect_to categories_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def category_params
    params.require(:category).permit(:name, :photo)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/bookmarks/new.html.erb
<div class="form-new">
  <h3>Add a Recipe to <%= @category.name %></h3>

  <%= simple_form_for [@category, @bookmark] do |f| %>
    <%= f.association :recipe %>
    <%= f.input :comment, placeholder: "Your comment here..." %>
    <%= f.submit 'Add Recipe', class:"btn btn-info"%>
  <% end %>

  <p>Back to <%= link_to @category.name, category_path(@category) %> </p>
</div>

app/views/categories/index.html.erb
<div class="banner" style="background-image: url('<%= image_path "banner.jpg"%>')">
  <div>
    <h1>CookBook</h1>
    <h3>Save your favourite recipes</h3>
  </div>
</div>

<div class="container w-75">
  <div class="info-top">
    <h1>List of Categories</h1>
    <%= link_to new_category_path, class: "btn btn-gradient" do %>
      <p>New Category</p>
    <% end %>
  </div>


  <div class ="cards">
    <% @categories.each do |category| %>
      <%= link_to category_path(category)  do%>
      <div class="card-category" style="background-image: url('<%= cl_image_path category.photo.key, crop: :fill %>')">
        <h3> <%= category.name %> </h3>
        <p> <%= category.recipes.count %> recipes </p>
      </div>
    <% end %>
    <% end %>
  </div>
</div>

app/views/categories/new.html.erb
<div class="form-new">
  <h3>Add a new Category </h1>

  <%= simple_form_for (@category) do |f| %>
    <%= f.input :name, placeholder: "The category name..."%>
    <%= f.input :photo, as: :file %>
    <%= f.submit class:"btn btn-info" %>
  <% end %>

  <%= link_to "Back to Categories", categories_path %>
</div>

app/views/categories/show.html.erb
<div class="banner" style="background-image: url('<%= cl_image_path @category.photo.key %>')">
  <h1><%= @category.name %> </h1>
</div>


<div class="container w-75">
  <div class="info-top">
    <h1>Recipes</h1>
    <%= link_to "Add Recipe", new_category_bookmark_path(@category.id), class:"btn btn-gradient"%>
  </div>

<div class="cards">
  <% @category.bookmarks.each do |bookmark| %>
  <div class="card-trip">
    <img src="<%= bookmark.recipe.image_url %>" alt="<%= bookmark.recipe.name %> image">
    <%= link_to bookmark_path(bookmark), data: {turbo_method: :delete, turbo_confirm:"Are you sure?"}, class:'btn btn-delete' do %>
      <i class="fa-solid fa-trash"></i>
    <% end %>
      <div class="card-trip-infos">
        <div>
          <h2><%= bookmark.recipe.name %></h2>
          <p><%= bookmark.recipe.description.truncate(80) %></p>
        </div>
      </div>
      <div class="bottom-info">
        <h6>❝<%= bookmark.comment %></h6>
        <p class="card-trip-pricing"> <%= bookmark.recipe.rating %><%= "⭐️" * bookmark.recipe.rating %> </p>
      </div>
  </div>
  <% end %>
</div>
</div>


<%# <%= cl_image_tag @article.photo.key, height: 300, width: 400, crop: :fill %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsCookbook</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
   <%= render "shared/navbar" %>
    <%= yield %>
  </body>
</html>

app/views/shared/_navbar.html.erb
<div class="navbar">
  <%= image_tag "/assets/138665167_10422729.png" %>

<div>
  <%= link_to"Home", root_path %>
  <%= link_to"New Category", new_category_path %>
</div>
</div>